import Head from 'next/head'
import ProductTable from './Components/ProductTable/ProductTable'
import StylePartner from './stylePartner.module.css'
import Pagination from './Components/Pagination/Pagination'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div className={StylePartner.titlePartner}>Productos del proveedor</div>
       <ProductTable></ProductTable>
       <Pagination></Pagination>
      </main>
    </>
  )
}